/*
 *  Module: Port
 *  File Name: Port_PBcfg.c
 *  Description: Post Build Configuration Source file for Port Module.
 *  Author: Ahmed Zahwy
 */

#include "MemMap.h"
#include "Port.h"				/* Header file for Port Module. */

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif


/* PB structure used with Dio_Init API */
const Port_ConfigType Port_Configuration =
                                   {
                                		   {
                                				   {PORTCONFG_PA0_PORT_NUM,
                                				    PORTCONFG_PA0_PIN_NUM,
													PORTCONFG_PA0_INITIAL_MODE,
													PORTCONFG_PA0_INITIAL_DIRECTION,
													PORTCONFG_PA0_INITIAL_LEVEL,
													PORTCONFG_PA0_DIRECTION_CHANGEABLE,
													PORTCONFG_PA0_MODE_CHANGEABLE,
													PORTCONFG_PA0_ACTIVATE_PULLUP},

                                				   {PORTCONFG_PA1_PORT_NUM,
                                				    PORTCONFG_PA1_PIN_NUM,
													PORTCONFG_PA1_INITIAL_MODE,
													PORTCONFG_PA1_INITIAL_DIRECTION,
													PORTCONFG_PA1_INITIAL_LEVEL,
													PORTCONFG_PA1_DIRECTION_CHANGEABLE,
													PORTCONFG_PA1_MODE_CHANGEABLE,
													PORTCONFG_PA1_ACTIVATE_PULLUP},

                                				   {PORTCONFG_PA2_PORT_NUM,
                                				    PORTCONFG_PA2_PIN_NUM,
													PORTCONFG_PA2_INITIAL_MODE,
													PORTCONFG_PA2_INITIAL_DIRECTION,
													PORTCONFG_PA2_INITIAL_LEVEL,
													PORTCONFG_PA2_DIRECTION_CHANGEABLE,
													PORTCONFG_PA2_MODE_CHANGEABLE,
													PORTCONFG_PA2_ACTIVATE_PULLUP},

                                				   {PORTCONFG_PA3_PORT_NUM,
                                				    PORTCONFG_PA3_PIN_NUM,
													PORTCONFG_PA3_INITIAL_MODE,
													PORTCONFG_PA3_INITIAL_DIRECTION,
													PORTCONFG_PA3_INITIAL_LEVEL,
													PORTCONFG_PA3_DIRECTION_CHANGEABLE,
													PORTCONFG_PA3_MODE_CHANGEABLE,
													PORTCONFG_PA3_ACTIVATE_PULLUP},

												   {PORTCONFG_PA4_PORT_NUM,
	                                				PORTCONFG_PA4_PIN_NUM,
													PORTCONFG_PA4_INITIAL_MODE,
													PORTCONFG_PA4_INITIAL_DIRECTION,
													PORTCONFG_PA4_INITIAL_LEVEL,
													PORTCONFG_PA4_DIRECTION_CHANGEABLE,
													PORTCONFG_PA4_MODE_CHANGEABLE,
													PORTCONFG_PA4_ACTIVATE_PULLUP},

												   {PORTCONFG_PA5_PORT_NUM,
													PORTCONFG_PA5_PIN_NUM,
													PORTCONFG_PA5_INITIAL_MODE,
													PORTCONFG_PA5_INITIAL_DIRECTION,
													PORTCONFG_PA5_INITIAL_LEVEL,
													PORTCONFG_PA5_DIRECTION_CHANGEABLE,
													PORTCONFG_PA5_MODE_CHANGEABLE,
													PORTCONFG_PA5_ACTIVATE_PULLUP},

												   {PORTCONFG_PA6_PORT_NUM,
													PORTCONFG_PA6_PIN_NUM,
													PORTCONFG_PA6_INITIAL_MODE,
													PORTCONFG_PA6_INITIAL_DIRECTION,
													PORTCONFG_PA6_INITIAL_LEVEL,
													PORTCONFG_PA6_DIRECTION_CHANGEABLE,
													PORTCONFG_PA6_MODE_CHANGEABLE,
													PORTCONFG_PA6_ACTIVATE_PULLUP},

												   {PORTCONFG_PA7_PORT_NUM,
													PORTCONFG_PA7_PIN_NUM,
													PORTCONFG_PA7_INITIAL_MODE,
													PORTCONFG_PA7_INITIAL_DIRECTION,
													PORTCONFG_PA7_INITIAL_LEVEL,
													PORTCONFG_PA7_DIRECTION_CHANGEABLE,
													PORTCONFG_PA7_MODE_CHANGEABLE,
													PORTCONFG_PA7_ACTIVATE_PULLUP},


												   {PORTCONFG_PB0_PORT_NUM,
													PORTCONFG_PB0_PIN_NUM,
													PORTCONFG_PB0_INITIAL_MODE,
													PORTCONFG_PB0_INITIAL_DIRECTION,
													PORTCONFG_PB0_INITIAL_LEVEL,
													PORTCONFG_PB0_DIRECTION_CHANGEABLE,
													PORTCONFG_PB0_MODE_CHANGEABLE,
													PORTCONFG_PB0_ACTIVATE_PULLUP},

												   {PORTCONFG_PB1_PORT_NUM,
													PORTCONFG_PB1_PIN_NUM,
													PORTCONFG_PB1_INITIAL_MODE,
													PORTCONFG_PB1_INITIAL_DIRECTION,
													PORTCONFG_PB1_INITIAL_LEVEL,
													PORTCONFG_PB1_DIRECTION_CHANGEABLE,
													PORTCONFG_PB1_MODE_CHANGEABLE,
													PORTCONFG_PB1_ACTIVATE_PULLUP},

												   {PORTCONFG_PB2_PORT_NUM,
													PORTCONFG_PB2_PIN_NUM,
													PORTCONFG_PB2_INITIAL_MODE,
													PORTCONFG_PB2_INITIAL_DIRECTION,
													PORTCONFG_PB2_INITIAL_LEVEL,
													PORTCONFG_PB2_DIRECTION_CHANGEABLE,
													PORTCONFG_PB2_MODE_CHANGEABLE,
													PORTCONFG_PB2_ACTIVATE_PULLUP},

												   {PORTCONFG_PB3_PORT_NUM,
													PORTCONFG_PB3_PIN_NUM,
													PORTCONFG_PB3_INITIAL_MODE,
													PORTCONFG_PB3_INITIAL_DIRECTION,
													PORTCONFG_PB3_INITIAL_LEVEL,
													PORTCONFG_PB3_DIRECTION_CHANGEABLE,
													PORTCONFG_PB3_MODE_CHANGEABLE,
													PORTCONFG_PB3_ACTIVATE_PULLUP},

												   {PORTCONFG_PB4_PORT_NUM,
													PORTCONFG_PB4_PIN_NUM,
													PORTCONFG_PB4_INITIAL_MODE,
													PORTCONFG_PB4_INITIAL_DIRECTION,
													PORTCONFG_PB4_INITIAL_LEVEL,
													PORTCONFG_PB4_DIRECTION_CHANGEABLE,
													PORTCONFG_PB4_MODE_CHANGEABLE,
													PORTCONFG_PB4_ACTIVATE_PULLUP},

												   {PORTCONFG_PB5_PORT_NUM,
													PORTCONFG_PB5_PIN_NUM,
													PORTCONFG_PB5_INITIAL_MODE,
													PORTCONFG_PB5_INITIAL_DIRECTION,
													PORTCONFG_PB5_INITIAL_LEVEL,
													PORTCONFG_PB5_DIRECTION_CHANGEABLE,
													PORTCONFG_PB5_MODE_CHANGEABLE,
													PORTCONFG_PB5_ACTIVATE_PULLUP},

												   {PORTCONFG_PB6_PORT_NUM,
													PORTCONFG_PB6_PIN_NUM,
													PORTCONFG_PB6_INITIAL_MODE,
													PORTCONFG_PB6_INITIAL_DIRECTION,
													PORTCONFG_PB6_INITIAL_LEVEL,
													PORTCONFG_PB6_DIRECTION_CHANGEABLE,
													PORTCONFG_PB6_MODE_CHANGEABLE,
													PORTCONFG_PB6_ACTIVATE_PULLUP},

												   {PORTCONFG_PB7_PORT_NUM,
													PORTCONFG_PB7_PIN_NUM,
													PORTCONFG_PB7_INITIAL_MODE,
													PORTCONFG_PB7_INITIAL_DIRECTION,
													PORTCONFG_PB7_INITIAL_LEVEL,
													PORTCONFG_PB7_DIRECTION_CHANGEABLE,
													PORTCONFG_PB7_MODE_CHANGEABLE,
													PORTCONFG_PB7_ACTIVATE_PULLUP},


												   {PORTCONFG_PC0_PORT_NUM,
													PORTCONFG_PC0_PIN_NUM,
													PORTCONFG_PC0_INITIAL_MODE,
													PORTCONFG_PC0_INITIAL_DIRECTION,
													PORTCONFG_PC0_INITIAL_LEVEL,
													PORTCONFG_PC0_DIRECTION_CHANGEABLE,
													PORTCONFG_PC0_MODE_CHANGEABLE,
													PORTCONFG_PC0_ACTIVATE_PULLUP},

												   {PORTCONFG_PC1_PORT_NUM,
													PORTCONFG_PC1_PIN_NUM,
													PORTCONFG_PC1_INITIAL_MODE,
													PORTCONFG_PC1_INITIAL_DIRECTION,
													PORTCONFG_PC1_INITIAL_LEVEL,
													PORTCONFG_PC1_DIRECTION_CHANGEABLE,
													PORTCONFG_PC1_MODE_CHANGEABLE,
													PORTCONFG_PC1_ACTIVATE_PULLUP},

												   {PORTCONFG_PC2_PORT_NUM,
													PORTCONFG_PC2_PIN_NUM,
													PORTCONFG_PC2_INITIAL_MODE,
													PORTCONFG_PC2_INITIAL_DIRECTION,
													PORTCONFG_PC2_INITIAL_LEVEL,
													PORTCONFG_PC2_DIRECTION_CHANGEABLE,
													PORTCONFG_PC2_MODE_CHANGEABLE,
													PORTCONFG_PC2_ACTIVATE_PULLUP},

												   {PORTCONFG_PC3_PORT_NUM,
													PORTCONFG_PC3_PIN_NUM,
													PORTCONFG_PC3_INITIAL_MODE,
													PORTCONFG_PC3_INITIAL_DIRECTION,
													PORTCONFG_PC3_INITIAL_LEVEL,
													PORTCONFG_PC3_DIRECTION_CHANGEABLE,
													PORTCONFG_PC3_MODE_CHANGEABLE,
													PORTCONFG_PC3_ACTIVATE_PULLUP},

												   {PORTCONFG_PC4_PORT_NUM,
													PORTCONFG_PC4_PIN_NUM,
													PORTCONFG_PC4_INITIAL_MODE,
													PORTCONFG_PC4_INITIAL_DIRECTION,
													PORTCONFG_PC4_INITIAL_LEVEL,
													PORTCONFG_PC4_DIRECTION_CHANGEABLE,
													PORTCONFG_PC4_MODE_CHANGEABLE,
													PORTCONFG_PC4_ACTIVATE_PULLUP},

												   {PORTCONFG_PC5_PORT_NUM,
													PORTCONFG_PC5_PIN_NUM,
													PORTCONFG_PC5_INITIAL_MODE,
													PORTCONFG_PC5_INITIAL_DIRECTION,
													PORTCONFG_PC5_INITIAL_LEVEL,
													PORTCONFG_PC5_DIRECTION_CHANGEABLE,
													PORTCONFG_PC5_MODE_CHANGEABLE,
													PORTCONFG_PC5_ACTIVATE_PULLUP},

												   {PORTCONFG_PC6_PORT_NUM,
													PORTCONFG_PC6_PIN_NUM,
													PORTCONFG_PC6_INITIAL_MODE,
													PORTCONFG_PC6_INITIAL_DIRECTION,
													PORTCONFG_PC6_INITIAL_LEVEL,
													PORTCONFG_PC6_DIRECTION_CHANGEABLE,
													PORTCONFG_PC6_MODE_CHANGEABLE,
													PORTCONFG_PC6_ACTIVATE_PULLUP},

												   {PORTCONFG_PC7_PORT_NUM,
													PORTCONFG_PC7_PIN_NUM,
													PORTCONFG_PC7_INITIAL_MODE,
													PORTCONFG_PC7_INITIAL_DIRECTION,
													PORTCONFG_PC7_INITIAL_LEVEL,
													PORTCONFG_PC7_DIRECTION_CHANGEABLE,
													PORTCONFG_PC7_MODE_CHANGEABLE,
													PORTCONFG_PC7_ACTIVATE_PULLUP},


												   {PORTCONFG_PD0_PORT_NUM,
													PORTCONFG_PD0_PIN_NUM,
													PORTCONFG_PD0_INITIAL_MODE,
													PORTCONFG_PD0_INITIAL_DIRECTION,
													PORTCONFG_PD0_INITIAL_LEVEL,
													PORTCONFG_PD0_DIRECTION_CHANGEABLE,
													PORTCONFG_PD0_MODE_CHANGEABLE,
													PORTCONFG_PD0_ACTIVATE_PULLUP},

												   {PORTCONFG_PD1_PORT_NUM,
													PORTCONFG_PD1_PIN_NUM,
													PORTCONFG_PD1_INITIAL_MODE,
													PORTCONFG_PD1_INITIAL_DIRECTION,
													PORTCONFG_PD1_INITIAL_LEVEL,
													PORTCONFG_PD1_DIRECTION_CHANGEABLE,
													PORTCONFG_PD1_MODE_CHANGEABLE,
													PORTCONFG_PD1_ACTIVATE_PULLUP},

												   {PORTCONFG_PD2_PORT_NUM,
													PORTCONFG_PD2_PIN_NUM,
													PORTCONFG_PD2_INITIAL_MODE,
													PORTCONFG_PD2_INITIAL_DIRECTION,
													PORTCONFG_PD2_INITIAL_LEVEL,
													PORTCONFG_PD2_DIRECTION_CHANGEABLE,
													PORTCONFG_PD2_MODE_CHANGEABLE,
													PORTCONFG_PD2_ACTIVATE_PULLUP},

												   {PORTCONFG_PD3_PORT_NUM,
													PORTCONFG_PD3_PIN_NUM,
													PORTCONFG_PD3_INITIAL_MODE,
													PORTCONFG_PD3_INITIAL_DIRECTION,
													PORTCONFG_PD3_INITIAL_LEVEL,
													PORTCONFG_PD3_DIRECTION_CHANGEABLE,
													PORTCONFG_PD3_MODE_CHANGEABLE,
													PORTCONFG_PD3_ACTIVATE_PULLUP},

												   {PORTCONFG_PD4_PORT_NUM,
													PORTCONFG_PD4_PIN_NUM,
													PORTCONFG_PD4_INITIAL_MODE,
													PORTCONFG_PD4_INITIAL_DIRECTION,
													PORTCONFG_PD4_INITIAL_LEVEL,
													PORTCONFG_PD4_DIRECTION_CHANGEABLE,
													PORTCONFG_PD4_MODE_CHANGEABLE,
													PORTCONFG_PD4_ACTIVATE_PULLUP},

												   {PORTCONFG_PD5_PORT_NUM,
													PORTCONFG_PD5_PIN_NUM,
													PORTCONFG_PD5_INITIAL_MODE,
													PORTCONFG_PD5_INITIAL_DIRECTION,
													PORTCONFG_PD5_INITIAL_LEVEL,
													PORTCONFG_PD5_DIRECTION_CHANGEABLE,
													PORTCONFG_PD5_MODE_CHANGEABLE,
													PORTCONFG_PD5_ACTIVATE_PULLUP},

												   {PORTCONFG_PD6_PORT_NUM,
													PORTCONFG_PD6_PIN_NUM,
													PORTCONFG_PD6_INITIAL_MODE,
													PORTCONFG_PD6_INITIAL_DIRECTION,
													PORTCONFG_PD6_INITIAL_LEVEL,
													PORTCONFG_PD6_DIRECTION_CHANGEABLE,
													PORTCONFG_PD6_MODE_CHANGEABLE,
													PORTCONFG_PD6_ACTIVATE_PULLUP},

												   {PORTCONFG_PD7_PORT_NUM,
													PORTCONFG_PD7_PIN_NUM,
													PORTCONFG_PD7_INITIAL_MODE,
													PORTCONFG_PD7_INITIAL_DIRECTION,
													PORTCONFG_PD7_INITIAL_LEVEL,
													PORTCONFG_PD7_DIRECTION_CHANGEABLE,
													PORTCONFG_PD7_MODE_CHANGEABLE,
													PORTCONFG_PD7_ACTIVATE_PULLUP}
                                		   }
								   };
